- name: check container
  docker_container:
    name: tomcat
    image: tomcat
    state: present

- name: remove container
  docker_container:
    name: tomcat
    image: tomcat
    state: absent

- name: create container
  docker_container:
    name: tomcat
    image: tomcat
    ports: 8010